name: Docker

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

    # Push the Docker image to the GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

